# Generated by Django 2.1.3 on 2018-11-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(max_length=255)),
                ('catagory', models.CharField(choices=[('python', 'Python'), ('ruby', 'Ruby'), ('javascript', 'Javascript')], max_length=20, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
