# Generated by Django 2.1.3 on 2018-11-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20181125_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
